allowBuilds:
  esbuild: true
  sharp: true
  unrs-resolver: true
  workerd: true
nodeLinker: hoisted
minimumReleaseAgeExclude:
  - miniflare@4.20260706.0
  - wrangler@4.108.0
onlyBuiltDependencies:
  - esbuild
  - sharp
  - unrs-resolver
  - workerd
